#mysql:
#  drivername: "mysql"
#  username: "root"
#  password: "123456"
#  host: "127.0.0.1"
#  port: 3306
#  database: "gin_blog_data"
#
#redis:
#  ip: "localhost"
#  port: 6379
#  password: ""
#  db: 0

